config/routes.rb
Hive::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => 'registrations'}

  root to: "welcome#index"
  
  resources :users do
    get 'card', :to => 'charges#new'
    post 'approve', :to => 'admin#approve'
  end
  
  resources :charges
  
  resources :admin
  
  resources :jobs do
    put 'accept_job', :to => 'jobs#accept'
    get 'pay', :to => 'charges#pay'
  end
  
  match '/about' => 'welcome#about'
  match '/terms' => 'welcome#terms'
  match '/privacy' => 'welcome#privacy'
  
  

end

app/models/job.rb
class Job < ActiveRecord::Base
  
  has_and_belongs_to_many :users
    
  attr_accessible :address_1, :address_2, :city, :date_time, :estimated_hours, :state, :work_type, :workers, :zip_code, :description, :user_id, :actual_hours, :pay_amount, :paid, :rating, :accepted, :actual_minutes
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_and_belongs_to_many :jobs
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address_1, :address_2, :city, :drive, :first_name, :last_name, :phone, :rating, :school, :state, :work_type, :zip_code, :admin, :role, :work_type_moving, :work_type_cleaning, :work_type_painting, :work_type_yard, :work_type_it, :work_type_tutor, :work_type_babysit, :work_type_event, :work_type_errands, :work_type_maintenance, :job_id, :stripe, :nps, :approved
  
  validates_presence_of :address_1, :city, :state, :phone, :zip_code, :role
  
  def save_stripe_customer_id(customer_id)
    update_attributes(:stripe => customer_id)
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    
    @users = User.all
    
    @worker_bees = User.where("role = ?", "Worker")
    @pending_wb = @worker_bees.where("approved = ?", false)
    
    @beekeepers = User.where("role = ?", "Keeper")
    
    hours_worked = Job.pluck(:actual_hours).reject!(&:nil?)
    
    @total_hours = hours_worked.empty? ? 0 : hours_worked.inject(:+)
    @total_revenue = @total_hours * 25
    
    
  end
  
  def approve
    
    @user = User.find(params[:user_id])
    
    @user.update_attribute(:approved, true)
    redirect_to :back, flash: { :notice => "Worker Bee successfully approved" }
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_index_path
    else
      user_path(current_user)
    end
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < JobsController
  
  def new
    
  end

  def create
    
     Stripe.api_key = "sk_test_1NQai375Xxj1lKFlXyYkGXJ1"
    
    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create a Customer
    customer = Stripe::Customer.create(
      :card => token,
      :email => current_user.email,
      :description => current_user.first_name + current_user.last_name
    )

    # Save the customer ID in your database so you can use it later
    current_user.save_stripe_customer_id(customer.id)
    
    redirect_to user_path(current_user), :flash => { :notice => "Thank you for signing up as a Beekeeper" }   

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
  
  def pay
    
    @job = Job.find(params[:job_id])
    
    @amount = @job.pay_amount * 100
    
    # Later...
    customer_id = current_user.stripe

    Stripe::Charge.create(
      :customer => customer_id,
      :amount   => @amount,
      :description => @job.id.to_s + " " + @job.work_type + " " + @job.date_time.strftime("%D %l:%M %P"),
      :currency => "usd"
    )
    
    @job.update_attribute(:paid, true)
    
    redirect_to user_path(current_user), :flash => { :notice => "Thank you for your payment" }   

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @jobs = current_user.jobs.all
  end
 
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.create(params[:job])
    current_user.jobs << @job
    redirect_to user_path(current_user)
  end
  
  def edit
    @job = Job.find(params[:id])
  end
  
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      hours = @job.actual_hours
      if @job.actual_minutes == 0 or 15
        @job.update_attribute(:actual_hours, hours)
      else
        @job.update_attribute(:actual_hours, hours+1)
      end
        @job.update_attribute(:pay_amount, 25 * (@job.actual_hours * @job.workers))
      
      if current_user.role == "Worker"
        redirect_to user_path(current_user)
      else
        if current_user.stripe != nil
          redirect_to job_pay_path(@job)
        else
          redirect_to user_card_path(current_user)
        end
      end
      
    else
      render 'edit'
    end
  end
  
  def show
    @job = Job.find(params[:id])
  end
  
  def accept
    @job = Job.find(params[:job_id])
    current_user.jobs << @job
    @job.update_attribute(:accepted, true)
    redirect_to user_path(current_user) 
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    if current_user.role == "Worker"
      edit_user_path(current_user)
    else
      user_card_path(current_user)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end
  
  def show
    
    @user = current_user
    
    @new_job = Job.new
    
    # Beekeepers
    @completed_work = current_user.jobs.where("date_time < ?", Date.today).where("accepted = ?", true)
    
    @scheduled_work = current_user.jobs.where("date_time > ?", Date.today)
    
    # Worker Bees
    
    @active_jobs = current_user.jobs.where("date_time > ?", Date.today).where("accepted = ?", true)
    
    @work_history = current_user.jobs.where("date_time < ?", Date.today)
    
    @opportunities = Job.where("date_time > ?", Date.today)
    
    hours_worked = current_user.jobs.collect(&:actual_hours).reject!(&:nil?)
    
    @total_hours = hours_worked.empty? ? 0 : hours_worked.inject(:+)
    @total_paid = @total_hours * current_user.pay_level rescue "N/A"
    
    
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
  def about
  end
  
  def terms
  end
  
  def privacy
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/admin/index.html.erb
<div class="container">
	<br>
	<% if current_user.admin? %>
	<ul class="nav nav-tabs honey">
	    <li class="active"><a href="#tab1" data-toggle="tab">User Stats</a></li>
	    <li><a href="#tab2" data-toggle="tab">Pending Worker Bees</a></li>
	  </ul>
	
	
	  <div class="tab-content">
	    <div class="tab-pane active" id="tab1">
				
	<legend>User Stats</legend>
	
  <table class="table table-striped table-hover">
		<tbody>
		<tr>
			<th>Total Users</th>
			<td><%= @users.count %></td>
		</tr>
		<tr>
			<th>Total Worker Bees</th>
			<td><%= @worker_bees.count %></td>
		</tr>
		<tr>
			<th>Pending Worker Bees</th>
			<td><%= @pending_wb.count %></td>
		</tr>
		<tr>
			<th>Total Beekeepers</th>
			<td><%= @beekeepers.count %></td>
		</tr>
		<tr>
			<th>Total Work Hours</th>
			<td><%= @total_hours %></td>
		</tr>
		<tr>
			<th>Total Revenue collected</th>
			<td>$<%= @total_revenue %></td>
		</tr>
		<tr>
			<th>Total Paid to Worker Bees</th>
			<td>$<%= @total_hours * 10 %></td>
		</tr>
		<tr>
			<th>Net HH Income</th>
			<td>$<%= @total_hours * 15 %></td>
		</tr>
	</body>
	</table>
	
</div>

<div class="tab-pane" id="tab2">
	
	<legend>Pending Worker Bees</legend>
	
  <table class="table table-striped table-hover">
		<thead>
		<tr>
			<th>User ID</th>
			<th>Name</th>
			<th>School</th>
			<th>Dirve</th>
			<th>Job Interest</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Approve</th>
		</tr>
	</thead>
	<tbody>
		<% @pending_wb.each do |w| %>
		<tr>
			<td><%= w.id %></td>
			<td><%= w.first_name + " " + w.last_name %></td>
			<td><%= w.school %></td>
			<td><%= w.drive ? "Yes" : "No" %></td>
			<td><%= w.work_type %></td>
			<td><%= mail_to w.email %></td>
			<td><%= number_to_phone(w.phone, area_code: true) %></td>
			<td><%= link_to "Approve", user_approve_path(w), method: "POST" %></td>
		</tr>
		<% end %>
	</tbody>
	</table>
	
</div>
</div>

<% else %>

You must be an administrator to view this page.

<% end %>
	
</div>
<br>

app/views/charges/new.html.erb
<div class="container">
	<br>

Please click the button to provide your credit card information. Your card will only be charged when a posted job is completed.

<%= form_tag charges_path do %>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="pk_test_S5BeEHURB93CACh6X9dkhI4y"
          data-description="Thank you for signing up with The Hired Hive!"
          data-amount= "" ></script>
<% end %>

<br>
<%= link_to "Terms of Use", terms_path %>
<br>
</div>

app/views/charges/pay.html.erb
<div class="container">
	<br>
	<legend>Job ID: <%= @job.id.to_s %> Invoice</legend>

	<b>Date and Time:</b> <%= @job.date_time.strftime("%D %l:%M %P")%><br>
	<b>Work Type:</b> <%= @job.work_type %><br>
	<b>Description:</b> <%= @job.description %><br>
	<b># of Worker Bees:</b> <%= @job.workers %><br>
	<b># of Hours Worked:</b> <%= @job.actual_hours %> * $25 = <b><i>$<%= @job.actual_hours * 25 %></i></b><br>
	<b>Total Cost:</b> Hours Worked * # of Worker Bees = $<%= @job.pay_amount %>.00<br>
	<br>

	<button class="btn btn-primary"><%= link_to "Pay", job_pay_path(@job.id) %> </button>
	<br>
</div>

app/views/jobs/edit.html.erb
<div class="container">
	<br>
	<%= form_for(@job) do |f| %>
	
	<% if current_user.role == "Keeper" %>
	<div>
		<label><strong>Would you recommend your Worker Bee to a friend or family member?</strong></label>
		<label class="radio"><%= f.radio_button :rating, 5 %> 5 - Yes, definitely would</label>
		<label class="radio"><%= f.radio_button :rating, 4 %> 4</label>
		<label class="radio"><%= f.radio_button :rating, 3 %> 3 - Neutral</label>
		<label class="radio"><%= f.radio_button :rating, 2 %> 2</label>
		<label class="radio"><%= f.radio_button :rating, 1 %> 1 - No, definitely not</label>
	</div>
	<br>
	<% end %>
		<label><strong>Please specify Actual Time it took to complete the job</strong></label>
		<div class="form-inline">
		<span>Hours <%= f.select :actual_hours, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %></span> : <span><%= f.select :actual_minutes, [00, 15, 30, 45]%> Minutes</span>
	</div>
	<br>
	<div><small><strong>Note:</strong> All jobs equal to or greater than 30 minutes will round to the next hour for payment purposes.</small></div>
	<br>
	
	<%= f.submit "Confirm/Pay" %>
	
	<% end %>
	
</div>
<br>

app/views/jobs/index.html.erb
<div class="container">
	
My JObs <% @jobs.each do |j| %>
<ul><%= j.user_id %></ul>
<% end %>

</div>

app/views/jobs/show.html.erb
<div class="container">
	
	<legend><%= "Job ID: " + @job.id.to_s + " - " + @job.work_type + " on " + @job.date_time.strftime("%D at %l:%M %P") %></legend>
	
	<label>Worker Bees</label>
	<% @job.users.where("role = ?", "Worker").each do |w| %>
	<ol>
		<li><%= w.first_name + " " + w.last_name + " | " + number_to_phone(w.phone, area_code: true) %></li>
	</ol>
	<% end %>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html >
<link rel="stylesheet" style="text/css" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.css" />
<html>
<head>
  <title>Hired Hive</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-inner">
			<a href="/" class="brand">
		    <%= image_tag("hive_yellow_small.png") %> The Hired Hive</a>
		    <ul class="nav pull-right">
					<li><%= link_to "Sign Up", new_user_registration_path if !user_signed_in? %></li>
					<% if user_signed_in? %>
					<li><%= link_to "Admin", admin_index_path if current_user.admin? %></li>
					<li><%= link_to "Dashboard", user_path(current_user) %></li>
					<li><%= link_to "Account", edit_user_registration_path %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, {:method => "DELETE"} %></li>
					<% end %>
		    </ul>
		  </div>
	</div>
	<div>
<%= yield %>
</div>
<div class="footer" >
	<p style="padding-top: 10px;">
		<ul class="footer-links">
			<li class="footer-links"><%= link_to "About", about_path %></li>
			<li class="footer-links"><%= link_to "Privacy Policy", privacy_path %></li>
			<li class="footer-links"><%= link_to "Terms", terms_path %></li>
		</ul></p>
  <p style="padding-left: 10px;">Copyright © 2013 Hired Hive, Inc.</p>
</div>


</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html >
<link rel="stylesheet" style="text/css" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.css" />
<html>
<head>
  <title>Hired Hive</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-inner">
			<a href="/" class="brand">
		    <%= image_tag("hive_yellow_small.png") %> Hired Hive</a>
		    <ul class="nav pull-right">
		      <li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Sign Up", new_user_registration_path if !user_signed_in? %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, {:method => "DELETE"} if user_signed_in? %></li>
		    </ul>
		  </div>
		
	</div>
	<div>
<%= yield %>
</div>
<div class="footer" >
    <p style="padding-left: 10px; padding-top: 30px;">Copyright © 2013 Hired Hive, Inc.</p>
</div>


</body>
</html>

app/views/users/_keeper.html.erb
<script type="text/javascript">
$(function(){
     $('.dropdown-toggle').dropdown();
});
</script>

<ul class="nav nav-tabs honey">
    <li class="active"><a href="#tab1" data-toggle="tab">Scheduled Jobs</a></li>
    <li><a href="#tab2" data-toggle="tab">Completed Jobs</a></li>
		<li><a href="#tab3" data-toggle="tab">Post New Job</a></li>
		<li><a href="#tab4" data-toggle="tab">Update Account</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <table class="table table-striped table-hover">
				<thead>
				<tr>
					<th>Job ID</th>
					<th>Date</th>
					<th>Time</th>
					<th>Est. Hours</th>
					<th>Location</th>
					<th>Work Type</th>
					<th>Description</th>
					<th>Worker Bee Info</th>
				</tr>
			</thead>
			<tbody>
				<% @scheduled_work.each do |j| %>
				<tr>
					<td><%= j.id %></td>
					<td><%= j.date_time.strftime("%D")%></td>
					<td><%= j.date_time.strftime("%l:%M %P")%></td>
					<td><%= j.estimated_hours %></td>
					<td><%= j.address_1 + " " + j.address_2 + " " + j.city + ", " + j.state %></td>
					<td><%= j.work_type %></td>
					<td><%= j.description %></td>
					<td><div class="btn-group">
  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
    Worker Bees
    <span class="caret"></span>
  </a>
  <ol class="dropdown-menu">
		<% j.users.where("role = ?", "Worker").each do |w| %>
    <li><%= w.first_name + " " + w.last_name%><br><%= number_to_phone(w.phone, area_code: true) %></li>
		<li class="divider"></li>
		<% end %>
  </ol>
</div></td>
				</tr>
				<% end %>
			</tbody>
			</table>
    </div>
	
    <div class="tab-pane" id="tab2">
      <table class="table table-striped table-hover">
				<thead>
				<tr>
					<th>Job ID</th>
					<th>Date</th>
					<th>Time</th>
					<th>Actual Hours</th>
					<th>Work Type</th>
					<th>Description</th>
					<th>Pay Amount</th>
					<th>Paid</th>
				</tr>
			</thead>
			<tbody>
				<% @completed_work.each do |j| %>
				<tr>
					<td><%= j.id %></td>
					<td><%= j.date_time.strftime("%D")%></td>
					<td><%= j.date_time.strftime("%l:%M %P")%></td>
					<td><%= j.actual_hours %></td>
					<td><%= j.work_type %></td>
					<td><%= j.description %></td>
					<td>$<%= j.pay_amount %></td>
					<td><%= j.paid ? "Yes" : (link_to "Confirm Work", edit_job_path(j)) %></td>
				</tr>
				<% end %>
			</tbody>
			</table>
    </div>
	
    <div class="tab-pane" id="tab3">
			<% if current_user.role == "Keeper" %>
      <%= render 'job' %>	
			<% else %>
			Sorry, you do not have permission to post jobs.
			<% end %>			
    </div>
	
    <div class="tab-pane" id="tab4">
			<%= form_for @user, :url => url_for(:controller => 'users', :action => 'update') do |f| %>
			<h4>Update Address</h4>
			<div class="form-horizontal">
				<label>Address Line One</label>
				<%= f.text_field :address_1, placeholder: "Address Line One" %>
				<label>Address Line Two</label>
				<%= f.text_field :address_2, placeholder: "Address Line Two" %>
			</div>
			<br>
			<div class="form-horizontal">
				<label>City</label>
				<%= f.text_field :city, placeholder: "City" %>
				<label>State</label>
				<%= f.text_field :state, placeholder: "State" %>
				<label>Zip_Code</label>
				<%= f.text_field :zip_code, placeholder: "Zip code" %>
			</div>
			<br>
			<div><%= f.submit "Update" %></div>

			<% end %>
    
    </div>

app/views/users/_worker.html.erb
<% if current_user.approved? %>
<ul class="nav nav-tabs honey">
    <li class="active"><a href="#tab1" data-toggle="tab">Active Jobs</a></li>
    <li><a href="#tab2" data-toggle="tab">Upcoming Opportunities</a></li>
		<li><a href="#tab3" data-toggle="tab">Work History</a></li>
		<li><a href="#tab4" data-toggle="tab">Account Info</a></li>
		<li><a href="#tab5" data-toggle="tab">Update Account</a></li>
  </ul>
	
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <table class="table table-striped table-hover">
				<thead>
				<tr>
					<th>Job ID</th>
					<th>Date</th>
					<th>Time</th>
					<th>Est. Hours</th>
					<th>Location</th>
					<th>Work Type</th>
					<th>Description</th>
					<th>Beekeeper</th>
					<th>Phone</th>
				</tr>
			</thead>
			<tbody>
				<% @active_jobs.each do |j| %>
				<tr>
					<td><%= j.id %></td>
					<td><%= j.date_time.strftime("%D")%></td>
					<td><%= j.date_time.strftime("%l:%M %P")%></td>
					<td><%= j.estimated_hours %></td>
					<td><%= j.address_1 + " " + j.address_2 + " " + j.city + ", " + j.state %></td>
					<td><%= j.work_type %></td>
					<td><%= j.description %></td>
					<td><%= j.users.where("role = ?", "Keeper").first.first_name + " " + j.users.where("role = ?", "Keeper").first.last_name %></td>
					<td><%= number_to_phone(j.users.where("role = ?", "Keeper").first.phone, area_code: true) %></td>
				</tr>
				<% end %>
			</tbody>
			</table>
    </div>
		
    <div class="tab-pane" id="tab2">
	    <div class="tab-pane active" id="tab1">
	      <table class="table table-striped table-hover">
					<thead>
					<tr>
						<th>Job ID</th>
						<th>Date</th>
						<th>Time</th>
						<th>Est. Hours</th>
						<th>Location</th>
						<th>Work Type</th>
						<th>Description</th>
						<th>Accept</th>
					</tr>
				</thead>
				<tbody>
					<% @opportunities.each do |j| %>
					<% if j.users.count < j.workers + 1 && j.users.any? { |u| u.id != current_user.id } %>
					<tr>
						<td><%= j.id %></td>
						<td><%= j.date_time.strftime("%D")%></td>
						<td><%= j.date_time.strftime("%l:%M %P")%></td>
						<td><%= j.estimated_hours %></td>
						<td><%= j.city + ", " + j.state %></td>
						<td><%= j.work_type %></td>
						<td><%= j.description %></td>
						<td><%= link_to "Accept", job_accept_job_path(j), method: :put %>
					</tr>
					<% end %>
					<% end %>
				</tbody>
				</table>
	    </div>
    </div>
		
    <div class="tab-pane" id="tab3">
      <table class="table table-striped table-hover">
				<thead>
				<tr>
					<th>Job ID</th>
					<th>Date</th>
					<th>Time</th>
					<th>Actual Hours</th>
					<th>Work Type</th>
					<th>Description</th>
					<th>Pay Amount</th>
					<th>Paid</th>
				</tr>
			</thead>
			<tbody>
				<% @work_history.each do |j| %>
				<tr>
					<td><%= j.id %></td>
					<td><%= j.date_time.strftime("%D")%></td>
					<td><%= j.date_time.strftime("%l:%M %P")%></td>
					<td><%= j.actual_hours %></td>
					<td><%= j.work_type %></td>
					<td><%= j.description %></td>
					<td>$<%= j.actual_hours * current_user.pay_level rescue "N/A" %></td>
					<td>
						<% if j.paid? %>
							Yes
						<% else %>
							<% if j.actual_hours != nil %>
								Pending...
							<% else %>
								<%= link_to "Get Paid", edit_job_path(j) %>
							<% end %>
						<% end %>
						</td>
				</tr>
				<% end %>
			</tbody>
			</table>
					
    </div>
			
    <div class="tab-pane" id="tab4">
			<table class="table table-striped table-hover">
				<tbody>
				<tr>
					<th>Jobs Completed</th>
					<td><%= @work_history.count %></td>
				</tr>
				<tr>
					<th>Amount Paid to Date</th>
					<td>$<%= @total_paid %></td>
				</tr>
				<tr>
					<th>Hours worked</th>
					<td><%= @total_hours %></td>
				</tr>
				<tr>
					<th>Current Pay Level</th>
					<td>$<%= current_user.pay_level %></td>
				</tr>
			</tbody>
			</table>
			
			<legend>Payment History</legend>
					
    </div>
		
    <div class="tab-pane" id="tab5">
			<%= form_for @user, :url => url_for(:controller => 'users', :action => 'update') do |f| %>
			<h4>Update your work preference</h4>
			<div class="form-inline">
				<label>School</label>
				<%= f.select :school, ['UNC Chapel Hill','UNC Wilmington'] %>
			</div>
			<br>
			<div class="form-horizontal">
				<label>Do you have access to a car?</label>
				<label><%= f.radio_button :drive, true %> Yes</label>
				<label><%= f.radio_button :drive, false%> No</label>
			</div>
			<br>
			<div class="form-horizontal">
				<label>What type of jobs are you interested in doing? <small>(Select all that apply)</small></label>
				<label><%= f.check_box :work_type_moving %> Moving</label>
				<label><%= f.check_box :work_type_cleaning %> Cleaning</label>
				<label><%= f.check_box :work_type_painting %> Painting</label>
				<label><%= f.check_box :work_type_yard %> Yard Work</label>
				<label><%= f.check_box :work_type_it %> IT Help</label>
				<label><%= f.check_box :work_type_tutor %> Tutoring</label>
				<label><%= f.check_box :work_type_babysit %> Babysitting</label>
				<label><%= f.check_box :work_type_event %> Event Help</label>
				<label><%= f.check_box :work_type_errands %> Household Errands</label>
				<label><%= f.check_box :work_type_maintenance %> Maintenance</label>
			</div>
			<br>

			<h4>Update Address</h4>
			<div class="form-horizontal">
				<label>Address Line One</label>
				<%= f.text_field :address_1, placeholder: "Address Line One" %>
				<label>Address Line Two</label>
				<%= f.text_field :address_2, placeholder: "Address Line Two" %>
			</div>
			<br>
			<div class="form-horizontal">
				<label>City</label>
				<%= f.text_field :city, placeholder: "City" %>
				<label>State</label>
				<%= f.text_field :state, placeholder: "State" %>
				<label>Zip_Code</label>
				<%= f.text_field :zip_code, placeholder: "Zip code" %>
			</div>
			<br>
			<div><%= f.submit "Update" %></div>

			<% end %>
      
    </div>
		
  </div>
	
	<% else %>

	Thank you for your interest in becoming a Worker Bee! Someone will contact you shortly to set up an interview.
	
	<% end %>

app/views/users/index.html.erb
<div class="container">


? Nothing yet.

</div>

<br>

app/views/welcome/index.html.erb
<div class="jumbotron">
	
	<div class="row-fluid">
		
		<div class="span8">
			
			<iframe width="700" height="315" src="//www.youtube.com/embed/sSk_ev1eZec" frameborder="0" allowfullscreen align="right"></iframe>
			
		</div>
		
		<div class="span4">
			<h4>Sign In</h4>
			<%= form_for("user", :url => user_session_path) do |f| %>
	  		<%= f.text_field :email, placeholder: "Email" %><br>
	 		 	<%= f.password_field :password, placeholder: "Password"%><br>
				<%= f.check_box :remember_me %>
				<%= f.label :remember_me %>
				<%= f.submit 'Sign in' %>
			<% end %>
			<%= link_to "Forgot your password?", new_password_path('user') %><p>
			<button class="btn btn-large btn-info honey"><%= link_to "Join Today", new_user_registration_path %></button>
		</div>
		
	</div>
	
</div>